version: "3"


services:
    db:
      restart: always
      environment:
        - POSTGRES_USER=omar
        - POSTGRES_PASSWORD=password
        - POSTGRES_HOST=db
        - POSTGRES_PORT=5432
      image: "postgres"
      ports:
      - "5432:5432"

    pos:
      build: .
      ports:
        - "5000:5000"
      depends_on:
        - db
      environment:
        - FLASK_APP=setup.py
        - POSTGRES_PASSWORD=db
        - POSTGRES_USER=db
        - POSTGRES_HOST=db
        - POSTGRES_PORT=db
        - POSTGRES_DB=db
      volumes:
        - .:/home/app
