version: '3'


services:
    db:
      image: "postgres"
      env_file:
        - ./config/db/db.env
      volumes:
        #- ./config/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        - database-data:/var/lib/postgresql/data
      ports:
      - "5432:5432"
      networks:
        - app-tier
      container_name: db_service


    pos:
      restart: always
      build: .
      volumes:
        - .:/home/app
      ports:
        - "3001:3001"
      networks:
        - app-tier
      depends_on:
        - db
      container_name: pos_service


networks:
  app-tier:
    driver: bridge
volumes:
  database-data:


